language: node_js
node_js:
- 4.0
before_install:
- npm install -g gulp-cli
install:
- npm install
after_success:
- chmod +x ./bin/create-release-tag.sh
- "./bin/create-release-tag.sh"
branches:
  except:
  - "/^v/"
deploy:
  provider: heroku
  api_key:
    secure: Aks2qWmMR4BnckDrFqm2iu7bxvXriAvDiIRDmQfqYWHsYr1DLNYGLnp7U0zTuJ06DutcKLvPM1Zr6BPXmb8BateUkbc9DHSGLGErUGhLECIuMbjhVbCctc6p55PlYnoTSZnjsV5ozIDEmasrWs79JPFct4T1cZCQTw/GNme1xyu9wOmteAHj+rmclNlt4ZloTIa+nfMXeMZjhT2dBv3G/gYMtZtpsXEhpjuEzebVUW8Zj1dQny+MLNhYQ99bukK9hlKh7dPejuGGiP6rZ4OtJiThweIEpZJx3/Fnx1yHS2lLHo+kcd9lUjT5lMJPWny4+8Xj/X523mkudqjYQROOkypEy8mQbO0I/KTNbBx0zOVtvDrtBjofxEjOqr0NhkMfgE9XzUe5EbLEPCdKmBNWZget6Fz6OK+wLXMjCat44CjVXjRlJdX6KDs7zfSFV9qdAgkUqSpqZWUjl+3STVCrxTmjCAeJoBl/u8ucF0vE0KpI2Ts3bJWrsxVlowLv0dB9TobHkAuRhc7yJ/b/l8w3k61EK/tKIqVhKc+aTjQ+oqtBa+Am6oPhk82wotUQBezXDt51vkRgl0GXBmE5nltr3aSO1S+TM90+DxiYmnL6AYSNQ+XTaAnnSl5toRzNFhXmTeQvPNOzBM4XpV6+gMZDa6MUZCXJ441zDnSN982PpG0=
  app: lcc-leedsgov-prototype
  on: master
notifications:
  email: false
sudo: false